print("Programa que identifica el tipo de dato de un valor ingresado por el usuario, se realizarán cinco interacciones:")
print("")
variable1=input("Primera Interacción, ingrese un valor cualquiera:")
print("Este tipo de dato en Python es:")
print(type(variable1))
print("")
variable2=input("Segunda Interacción, ingrese un valor cualquiera:")
print("Este tipo de dato en Python es:")
print(type(variable2))
print("")
variable3=input("Tercera Interacción, ingrese un valor cualquiera:")
print("Este tipo de dato en Python es:")
print(type(variable3))
print("")
variable4=input("Cuarta Interacción, ingrese un valor cualquiera:")
print("Este tipo de dato en Python es:")
print(type(variable4))
print("")
variable5=input("Quinta Interacción, ingrese un valor cualquiera:")
print("Este tipo de dato en Python es:")
print(type(variable5))
print("¡YA NO SE HARÁN MÁS INTERACCIONES!")
